version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - postfresql_data_secret_friend:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "secret-friend"

volumes:
  postfresql_data_secret_friend:
    driver: local
