# Generated by Django 3.2.16 on 2022-11-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profissional_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professional', 'Profissional'), ('patient', 'Paciente'), ('bot', 'Bot')], max_length=16, verbose_name='role'),
        ),
    ]
