# Generated by Django 3.2.16 on 2022-11-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221115_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='crm',
        ),
        migrations.AddField(
            model_name='profissional',
            name='register',
            field=models.CharField(blank=True, help_text='Exemplo de formato: 999999', max_length=255, null=True, verbose_name='Número de registro'),
        ),
    ]
